services:
  - type: web
    name: music-player
    env: static
    env:
      NODE_OPTIONS: "--openssl-legacy-provider"
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /
        destination: /index.html
